# Validator rpc end point(RPC of your own validator)
#useful to gather information about network info, validatr voting power, unconfirmed txns etc.
validator_rpc_endpoint = "http://localhost:26657"

# Operator address of your validator
#which will be used to get staking, delegation and distribution rewards.
val_operator_addr = "cosmosvaloper1dwwl3tumr7t5rswe674mczp0cq5xlf3af4m92q"

# Your validator account address
#which will be used to get account informtion etc
account_addr = "cosmos1dkwl3tumr7t5rswe674mczp1cq5xlf3avp0sxn"

# Validator hex address
#useful to know about last proposed block, missed blocks and voting power.
validator_hex_addr = "06E7798F67480B280BE14FE9B13D3BEBC933D89"

# Address of your lcd client
lcd_endpoint = "http://localhost:1317"

# External open RPC endpoint(secondary RPC other than your own validator).
#useful to gather information like validator caught up, syncing and missed blocks etc.
external_rpc = "http://50.112.14.10:26657"

# Configure the threshold to receive alert when the voting power reaches or drops below of the threshold given.
voting_power_threshold = 50

# Configure the threshold to get an alert if the no.of connected peers falls below the threshold.
num_peers_threshold = 1

# Configure the threshold to receive missed block alerting
missed_blocks_threshold = 4

# These are for regular status updates. 
# To receive validator status daily (twice), configure these parameters in the form of "02:25PM". The time here refers to UTC time.
alert_time1 = "02:30PM"
alert_time2 = "02:30AM"

# An integer value to receive block difference alerts
block_diff_threshold = 3

# Configure 'yes' if you wish to get telegram alerts otherwise make it 'no' .
enable_telegram_alerts = "yes"

#  Configure 'yes' if you wish to get email alerts otherwise make it 'no' .
enable_email_alerts = "yes"

# Give staking denom to display with self delegation balance
staking_denom = "uatom"

# Give your validator name to get it display in telegram and email messages
validator_name = "Validator Moniker"

# Give threshold to notify about continuous missed blocks to your pager duty account.
# so that it will send mails, messages and makes you a call about alerts.
emergency_missed_blocks_threshold = 50

# Give mail address of pager duty service to send alerts of emergency missed blocks
# Have to give mail address which was generated after creation of a service in pager duty.
pagerduty_email = "service@domain.pagerduty.com"

[scraper]
rate = "5s"
port = ":8080"
validator_rate = "60s"

[telegram]
# Telegram chat ID to receive telegram alerts
tg_chat_id = 228222105

# Telegram bot token. The bot should be added to the chat and it should have send message permission.
tg_bot_token = "1117273891:AAEtr35x4JRj5YSF4LBeu1fPFAJ4xj-UI"


[sendgrid]
# Sendgrid mail service api token.
sendgrid_token = ""

# E-mail address to receive mail notifications
email_address = "xyz@domain.com"

[influxdb]
port = "8086"
database = "vcf"
username = "admin"
