# Operator address of your validator
#Here it will be used to get staking of a validator.
val_operator_addr = "cosmosvaloper14l0fp639yudfl46zauvv8rkzjgd4u0zk2aseys"

# Validator hex address
#useful to know about missed blocks.
validator_hex_addr = "8F2927C1D0180B19087BB35DE19BABA4E0DE9238"

# Address of your lcd client
lcd_endpoint = "http://localhost:1317"

# External open RPC endpoint(secondary RPC other than your own validator).
#useful to gather information like validator caught up, syncing and missed blocks etc.
external_rpc = "http://localhost:26657"

# Name of your validator
#it will be displayed in telegram alerts
validator_name = "ValName"

# Daily alerts of validator status
alert_time1 = "07:23PM"
alert_time2 = "08:15AM"

[telegram]
tg_chat_id = 510331001
tg_bot_token="1117273891:AAEtr35x4JRj5YSF4LBeu1fPFAJ4xj-UK"

[sendgrid]
sendgrid_token = "1234567890"
email_address = "xyz@domain.com"
