val_operator_addr = "cosmosvaloper14l0fp639yudfl46zauvv8rkzjgd4u0zk2aseys"
account_addr = "cosmos14l0fp639yudfl46zauvv8rkzjgd4u0zk0fyvgr"
validator_hex_addr = "8F2927C1D0180B19087BB35DE19BABA4E0DE9238"
lcd_endpoint = "http://localhost:1317"
external_rpc = "http://localhost:26657"
validator_name = "witval"

# [alert-intervals]
alert_time1 = "07:23PM"
alert_time2 = "08:15AM"

[telegram]
tg_chat_id = 510331001
tg_bot_token="1234567890"

[sendgrid]
sendgrid_token = "1234567890"
email_address = "xyz@domain.com"
